spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USR:urusso}
    password: ${DATASOURCE_PWD:urussopwd}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
    hikari:
      maximum-pool-size: '5'
      schema: public
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: ${DATASOURCE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
    contexts: dev
    drop-first: false
    default-schema: public

cors:
  url: ${CORS_URL:http://localhost:4200}

springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

swagger:
  version: 1.0
  title: Spring Boot Example
  description: Swagger for the Spring Boot Example application

management:
  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:87a2198dc40441e38f7650ae755bbc2d464648e98096447dbe4fd924f202c7ac}
    expiration-time: ${JWT_EXPIRATION_TIME:3600000}

cache:
  jwt-ttl: 55 #minutes